### ISSUE TITLE
Null inquire please dont close, this is not resolved. 

### ISSUE THREAD

**Issue by Liferocka** [keijiro/ScriptGeneratorTest#11]
Hi, I would appreciate if you don't close this, we are not resolved. really.  So I looked into my usage and I still have soem. in my free trial. this image shoes this right? https://www.dropbox.com/s/z1o9l6mfpc7pduf/Screen%20Shot%202023-03-20%20at%203.28.48%20AM.png?dl=0

or do you have any other ideas why Im getting these Null erros.  again, Id like to get this to work.

**Comment by keijiro** [comment]
I reopened #10 , so I close this as duplicated.
