### ISSUE TITLE
Two errors

### ISSUE THREAD

**Issue by MarshallLaw-1** [keijiro/ScriptGeneratorTest#12]
![Screenshot (73)](https://user-images.githubusercontent.com/81347697/226330452-a8f4f3c5-22e1-487e-bc69-dac1bde09b98.png)
I am not sure how to resolve these issues any insight would be appreciated. Always looking to try and use aI to streamline my work on a budget.

**Comment by keijiro** [comment]
Please check the system requirement on README.

**Comment by keijiro** [comment]
I close this issue as answered. Please reopen it if it still reproduces after upgrading the Unity version.
