### ISSUE TITLE
Getting two errors upon startup

### ISSUE THREAD

**Issue by dradex** [keijiro/ScriptGeneratorTest#20]
Assets\Editor\OpenAIUtil.cs(28,28): error CS1503: Argument 2: cannot convert from 'string' to 'System.Collections.Generic.List<UnityEngine.Networking.IMultipartFormSection>'

Assets\Editor\OpenAIUtil.cs(28,59): error CS1503: Argument 3: cannot convert from 'string' to 'byte[]'

**Comment by keijiro** [comment]
Please check the system requirements on README.

**Comment by keijiro** [comment]
I close this issue now. Please reopen it for further issues.

**Comment by dradex** [comment]
alr thanks

**Comment by maajor** [comment]
So to use older version of unity, you could use this code 

```
byte[] databyte = Encoding.ASCII.GetBytes(CreateChatRequestBody(prompt));
        
// POST
var post = new UnityWebRequest(OpenAI.Api.Url, UnityWebRequest.kHttpVerbPOST);

post.uploadHandler = new UploadHandlerRaw(databyte);
post.downloadHandler = new DownloadHandlerBuffer();
post.SetRequestHeader("Content-Type", "application/json");

```

to replace

this part

https://github.com/keijiro/AICommand/blob/main/Assets/Editor/OpenAIUtil.cs#L27-L28
