### ISSUE TITLE
[Suggestion] you can use langchain.js in Unity

### ISSUE THREAD

**Issue by zombieyang** [keijiro/ScriptGeneratorTest#24]
So you can access OpenAI's API more easily.

https://github.com/puerts/unity-langchain-demo

------
https://hwchase17.github.io/langchainjs/docs/overview/
https://langchain.readthedocs.io/en/latest/index.html

**Comment by keijiro** [comment]
My understanding is that LangChain is useful for making the app API-agonistic (or should I say LLM agonistic?)

I made this project for the Unity-ChatGPT tutorial series, so I wouldn't like to extend it further.

Anyway, thanks for the suggestion. It looks very interesting. I'll consider integrating it in future projects.
