### ISSUE TITLE
Unity errors when opening up the project

### ISSUE THREAD

**Issue by Straviczki** [keijiro/ScriptGeneratorTest#28]
Assets\Editor\OpenAIUtil.cs(28,28): error CS1503: Argument 2: cannot convert from 'string' to 'System.Collections.Generic.List<UnityEngine.Networking.IMultipartFormSection>'

Assets\Editor\OpenAIUtil.cs(28,59): error CS1503: Argument 3: cannot convert from 'string' to 'byte[]'

Any idea of how i could tackle them?

**Comment by keijiro** [comment]
Please check the system requirements section on README.

**Comment by keijiro** [comment]
I close this issue as answered. Please reopen it if it still reproduces.
