### ISSUE TITLE
How to Install on Linux, Ubuntu?

### ISSUE THREAD

**Issue by Code-shaker** [keijiro/ScriptGeneratorTest#30]
It seems it just works on Windowsmachine, couldn't find the window "AI Command"by my Unity Version 2022.2.13f on ubuntu

**Comment by keijiro** [comment]
I developed this project on macOS. So, it's not Windows-only. I haven't tested it on Ubuntu but sure that it works on it.

Is there the "AI Command" item in the "Window" menu?

**Comment by Code-shaker** [comment]
The "AI Command" item in the "Window" menu is not available. Didn't know what I have to do.

**Comment by Code-shaker** [comment]
I am speechless,
Meanwhile I installed an different AI-tool "https://github.com/srcnalt/OpenAI-Unity" after that I looked again on the "Window" item and for unexplained reasons I could finaly find it. It works well.
