### ISSUE TITLE
console error

### ISSUE THREAD

**Issue by ww1123dd** [keijiro/ScriptGeneratorTest#31]
Why I run AIcommand it show this error?
NullReferenceException: Object reference not set to an instance of an object
AICommand.OpenAIUtil.InvokeChat (System.String prompt) (at Assets/AICommand-main/Assets/Editor/OpenAIUtil.cs:52)
AICommand.AICommandWindow.RunGenerator () (at Assets/AICommand-main/Assets/Editor/AICommandWindow.cs:38)
AICommand.AICommandWindow.OnGUI () (at Assets/AICommand-main/Assets/Editor/AICommandWindow.cs:64)
UnityEditor.HostView.OldOnGUI () (at <ae93fefe62eb49e6b9ef3807ffd33dc7>:0)

**Comment by keijiro** [comment]
Please check FAQ on README.
(Check if your credit card with your OpenAI account is valid)

**Comment by keijiro** [comment]
I close this issue. Please reopen it if it still reproduces.
