### ISSUE TITLE
Errors

### ISSUE THREAD

**Issue by llebedev** [keijiro/ScriptGeneratorTest#35]
Assets\Editor\OpenAIUtil.cs(28,28): error CS1503: Argument 2: cannot convert from 'string' to 'System.Collections.Generic.List<UnityEngine.Networking.IMultipartFormSection>'
 

and

Assets\Editor\OpenAIUtil.cs(28,59): error CS1503: Argument 3: cannot convert from 'string' to 'byte[]'

**Comment by keijiro** [comment]
Please check Unity version (see the system requirements on README).

**Comment by keijiro** [comment]
I close this issue as answered. Please reopen it if it still reproduces.
