### ISSUE TITLE
Safe Mode right off the bat

### ISSUE THREAD

**Issue by Omniscye** [keijiro/ScriptGeneratorTest#36]
Safe mode off the bat. Bytes to String, I do not understand

**Comment by keijiro** [comment]
Sorry but I can't understand what you're trying to tell. Compilation errors or something like that? If so, I'd recommend upgrading Unity to 2022.2 (as noted on README).

**Comment by keijiro** [comment]
I close this issue as answered. Please reopen it for further problems.
