### ISSUE TITLE
Error message: Assets\Editor\OpenAIUtil.cs(28,28): error CS1503: Argument 2: cannot convert from 'string' to 'System.Collections.Generic.List<UnityEngine.Networking.IMultipartFormSection>'

### ISSUE THREAD

**Issue by YY-nb** [keijiro/ScriptGeneratorTest#9]
When I copy the project and open it, Unity console has these error logs:
1. Assets\Editor\OpenAIUtil.cs(28,28): error CS1503: Argument 2: cannot convert from 'string' to 'System.Collections.Generic.List<UnityEngine.Networking.IMultipartFormSection>'
2. Assets\Editor\OpenAIUtil.cs(28,59): error CS1503: Argument 3: cannot convert from 'string' to 'byte[]'
How can I fix it?

**Comment by keijiro** [comment]
Could you check the system requirements on README?

**Comment by YY-nb** [comment]
> 

Sorry, I miss that important requirement. Thanks for your answer.
